version: '3.4'
services:
  api:
    build:
      context: .
      dockerfile: DOCKERFILE
    image: api
    command: ./bin/docker-entrypoint.sh
    volumes:
      - .:/code/src_files/
    ports:
      - "8000:8000"
    environment:
      - PROJECT_NAME
      - DEBUG=${DEBUG}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
